config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'activities#index'

  resources :activities
  resources :runs
  resources :workouts
end

app/models/activity.rb
# == Schema Information
#
# Table name: activities
#
#  id          :integer          not null, primary key
#  date        :date
#  start_time  :time
#  end_time    :time
#  description :text
#  location    :text
#  duration    :decimal(, )
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  distance    :decimal(, )
#

class Activity < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/run.rb
# == Schema Information
#
# Table name: activities
#
#  id          :integer          not null, primary key
#  date        :date
#  start_time  :time
#  end_time    :time
#  description :text
#  location    :text
#  duration    :decimal(, )
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  distance    :decimal(, )
#

class Run < Activity
end

app/models/workout.rb
# == Schema Information
#
# Table name: activities
#
#  id          :integer          not null, primary key
#  date        :date
#  start_time  :time
#  end_time    :time
#  description :text
#  location    :text
#  duration    :decimal(, )
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  distance    :decimal(, )
#

class Workout < Activity
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController

  def index
    @activities = Activity.paginate(:page => params[:page], per_page: 10)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/runs_controller.rb
class RunsController < ApplicationController

  def index
    @runs = Run.all
  end

  def show
    @run = Run.find(params[:id])
  end

  def new
    @run = Run.new
  end

  def create
    @run = Run.new(run_params)
    if @run.save
      redirect_to @run
    else
      render 'new'
    end
  end

  def edit
    @run = Run.find(params[:id])
  end

  def update
    @run = Run.find(params[:id])
    if @run.update(run_params)
      redirect_to @run
    else
      render 'new'
    end
  end

  def destroy
    @run = Run.find(params[:id])
    @run.destroy

    redirect_to runs_path
  end

  private

  def run_params
    params.require(:run).permit(
      :date,
      :start_time,
      :end_time,
      :description,
      :location,
      :distance,
    )
  end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController

  def index
    @workouts = Workout.all
  end

  def show
    @workout = Workout.find(params[:id])
  end

  def new
    @workout = Workout.new
  end

  def create
    @workout = Workout.new(workout_parms)
    if @workout.save
      redirect_to @workout
    else
      render 'new'
    end
  end

  def edit
    @workout = Workout.find(params[:id])
  end

  def update
    @workout = Workout.find(params[:id])
    if @workout.update(workout_parms)
      redirect_to @workout
    else
      render 'new'
    end
  end

  def destroy
    @workout = Workout.find(params[:id])
    @workout.destroy

    redirect_to runs_path
  end

  private

  def workout_parms
    params.require(:workout).permit(
      :date,
      :start_time,
      :end_time,
      :description,
      :location,
      :duration,
    )
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/runs_helper.rb
module RunsHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/activities/index.html.erb
<div class="row">
  <div class="col">
    <h1><span>Activities</span></h1>

    <div class="pagination col">
      <div class="page_info">
        <%= page_entries_info @activities %>
      </div>
      <%= will_paginate @activities, :container => false %>
    </div>

    <table>
      <thead>
        <tr>
          <th>Date</th>
          <th>Location</th>
          <th>Duration</th>
        </tr>
      </thead>

      <% @activities.each do |activity| %>
        <tbody>
          <tr>
            <td><%= activity.date %></td>
            <td><%= activity.location %></td>
            <td><%= activity.duration %>Minutes</td>
          </tr>
        </tbody>
      <% end %>

      </table>
    </br>


    <div class="col">
      <%= link_to 'Record new workout', new_workout_path, class: 'paper-btn' %>
      <%= link_to 'Record new run', new_run_path, class: 'paper-btn' %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tflangram</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

      <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-alpha.3/css/materialize.min.css">

    <!--Import jQuery before materialize.js-->
      <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
      <!-- Compiled and minified JavaScript -->
      <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-alpha.3/js/materialize.min.js"></script>



  <div class="navbar-fixed">
    <nav>
      <div class="nav-wrapper blue lighten-2">
        <%= link_to 'Activities', root_path, class: 'brand-logo' %>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li><a href="activities">Activities</a></li>
          <li><a href="runs">Runs</a></li>
          <li><a href="workouts">Workouts</a></li>
        </ul>
      </div>
    </nav>
  </div>

  <main>
    <body>
      <%= yield %>
    </body>
  </main>

  <footer class="page-footer blue lighten-2">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text">Footer Content</h5>
          <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
        </div>
        <div class="col l4 offset-l2 s12">
          <h5 class="white-text">Links</h5>
          <ul>
            <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
            <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
      © 2014 Copyright Text
      <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
      </div>
    </div>
  </footer>

</html>

app/views/runs/_form.html.erb
<div class="row">
  <form class="col s12">
    <div class="row">
      <%= form_for(@run, html: {multipart: true}) do |f| %>

        <div>
          <%= f.label :date %><br>
          <%= f.text_field :date, class: "datepicker" %>
        </div>

        <div class="input-field col s6">
          <%= f.label :start_time %><br>
          <%= f.time_field :start_time %>
        </div>

        <div class="input-field col s6">
          <%= f.label :end_time %><br>
          <%= f.time_field :end_time %>
        </div>

        <div class="input-field col s6">
          <%= f.label :location %><br>
          <%= f.text_field :location %>
        </div>

        <div class="input-field col s6">
          <%= f.label :distance %><br>
          <%= f.number_field :distance %>
        </div>

        <div class="input-field col s12">
          <%= f.label :description %>
          <%= f.text_field :description %>
        </p>

        <div class="col">
          <%= f.submit "Submit" %>
        </div>

      <% end %>

    </div>
  </form>
</div>

<script type="text/javascript">
   $('.datepicker').pickadate({
    selectMonths: true, // Creates a dropdown to control month
    selectYears: 15, // Creates a dropdown of 15 years to control year,
    today: 'Today',
    clear: 'Clear',
    close: 'Ok',
    closeOnSelect: false // Close upon selecting a date,
  });
</script>

app/views/runs/edit.html.erb
<div class='row'>
  <div class="col">
    <h3>Edit Run</h3>

    <%= render 'form' %>

    <%= link_to 'Cancel', runs_path %>
  </div>
</div>

app/views/runs/index.html.erb
<div class="row">
  <div class="col">
    <h1><span>Runs</span></h1>

    <table>
      <thead>
        <tr>
          <th>Date</th>
          <th>Location</th>
          <th>Distance</th>
        </tr>
      </thead>

      <% @runs.each do |run| %>
        <tbody>
          <tr>
            <td><%= run.date %></td>
            <td><%= run.location %></td>
            <td><%= run.distance %>Miles</td>
            <td><%= link_to 'View', run_path(run) %></td>
            <td><%= link_to 'Edit', edit_run_path(run) %></td>
          </tr>
        </tbody>
      <% end %>

    </table>

    <div class="col">
        <%= link_to 'Add', new_run_path, class: "btn-floating btn-large waves-effect waves-light red" %>
    </div>
  </div>
</div>

app/views/runs/new.html.erb
<div class='row'>
  <div class="col">
    <h1>Record New Run</h1>

    <%= render 'form' %>

    <%= link_to 'Cancel', runs_path %>
  </div>
</div>

app/views/runs/show.html.erb
<div class='row'>
  <div class="col">
    <h3><span>Run Details</span></h3>

    <p>
      <strong>Date:</strong>
      <%= @run.date %>
    </p>

    <p>
      <strong>Start Time:</strong>
      <%= @run.start_time %>
    </p>

    <p>
      <strong>End Time:</strong>
      <%= @run.end_time %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @run.description %>
    </p>

    <p>
      <strong>Location:</strong>
      <%= @run.location %>
    </p>
    <p>
      <strong>Distance:</strong>
      <%= @run.distance %> Miles
    </p></br>

    <p>
      <%= link_to 'Edit', edit_run_path(@run), class: 'paper-btn' %></br>
    </p>
    <p>
    <%= link_to 'Delete', run_path(@run),
            method: :delete,
            data: { confirm: 'Are you sure?' }, class: 'paper-btn' %></br>
    </p>
    <p>
    <%= link_to 'View All Runs', runs_path, class: 'paper-btn' %></br>
    </p>
  </div>
</div>

app/views/workouts/_form.html.erb
<div class="row">
  <form class="col s12">
    <div class="row">

      <%= form_for(@workout, html: {multipart: true}) do |f| %>

        <div type="text" class="datepicker">
          <%= f.label :date %><br>
          <%= f.date_select :date %>
        </div>

        <div class="input-field col s6">
          <%= f.label :start_time %><br>
          <%= f.time_field :start_time %>
        </div>

        <div class="input-field col s6">
          <%= f.label :end_time %><br>
          <%= f.time_field :end_time %>
        </div>

        <div class="input-field col s6">
          <%= f.label :location %><br>
          <%= f.text_field :location %>
        </div>

        <div class="input-field col s12">
          <%= f.label :duration %>
          <%= f.text_field :duration %>
        </p>

        <div class="col">
          <%= f.submit "Submit", class: "btn waves-effect waves-light" %>
        </div>

      <% end %>

    </div>
  </form>
</div>

app/views/workouts/edit.html.erb
<div class='row'>
  <div class="col">
    <h3>Edit Workout</h3>

    <%= render 'form' %>

    <%= link_to 'Cancel', workouts_path %>
  </div>
</div>

app/views/workouts/index.html.erb
<div class="row">
  <div class="col">
    <h1><span>Workouts</span></h1>

    <table>
      <thead>
        <tr>
          <th>Date</th>
          <th>Location</th>
          <th>Duration</th>
        </tr>
      </thead>

      <% @workouts.each do |workout| %>
        <tbody>
          <tr>
            <td><%= workout.date %></td>
            <td><%= workout.location %></td>
            <td><%= workout.duration %>Minutes</td>
            <td><%= link_to 'View', workout_path(workout) %></td>
            <td><%= link_to 'Edit', edit_workout_path(workout) %></td>
          </tr>
        </tbody>
      <% end %>

      </table>
    </br>

    <div class="col">
      <%= link_to '+', new_workout_path, class: 'btn-floating btn-large waves-effect waves-light red' %>
    </div>
  </div>
</div>

app/views/workouts/new.html.erb
<div class='row'>
  <div class="col">
    <h1>Record New Workout</h1>

    <%= render 'form' %>

    <%= link_to 'Cancel', workouts_path %>
  </div>
</div>

app/views/workouts/show.html.erb
<div class='row'>
  <div class="col">
    <h3><span>Workout Details</span></h3>
    <p>
      <strong>Date:</strong>
      <%= @workout.date %>
    </p>

    <p>
      <strong>Start Time:</strong>
      <%= @workout.start_time %>
    </p>

    <p>
      <strong>End Time:</strong>
      <%= @workout.end_time %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @workout.description %>
    </p>

    <p>
      <strong>Location:</strong>
      <%= @workout.location %>
    </p>
    <p>
      <strong>Duration:</strong>
      <%= @workout.duration %> Minutes
    </p>

    <p>
      <%= link_to 'Edit', edit_workout_path(@workout), class: 'paper-btn' %>
    </p>
    <p>
    <%= link_to 'Delete', workout_path(@workout),
            method: :delete,
            data: { confirm: 'Are you sure?' }, class: 'paper-btn' %>
  </p>
    <p>
      <%= link_to 'View All Workouts', workouts_path, class: 'paper-btn' %>
    </p>
  </div>
</div>